name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: [7.1, 7.2, 7.3, 7.4, "8.0"]
        kafka: [0.8.2.2-1,0.9.0.1-1,1.0.0, 2.11-1.1.1, 2.13-2.6.0, 2.13-2.7.0]

    env:
      PHP_VERSION: ${{ matrix.php }}
      KAFKA_VERSION: ${{ matrix.kafka }}
      SWOOLE_VERSION: "4.5"
      KAFKA_HOST: kafka1
      KAFKA_PLAINTEXT_PORT: 9092
      KAFKA_SASL_PLAINTEXT_PORT: 9093
      KAFKA_SASL_SSL_PORT: 9094
      KAFKA_SSL_PORT: 9095
      KAFKA_SASL: '{"type":"longlang\\phpkafka\\Sasl\\PlainSasl","username":"admin","password":"admin-secret"}'
      KAFKA_SSL: '{"open":true,"verifyPeer":true,"allowSelfSigned":true,"verifyPeerName":true,"cafile":"/kafka-client/.github/kafka/cert/ca-cert"}'

    steps:
      - uses: actions/checkout@v2

      - name: start docker
        run: |
          cd .github
          # run
          docker-compose up -d
          # swoole
          docker exec swoole php -v && docker exec swoole php --ri swoole && docker exec swoole composer -V
          docker ps -a && docker ps

      - name: prepare
        run: |
          docker exec swoole composer update
          docker exec kafka1 /opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper:2181 --create --partitions 3 --replication-factor 1 --topic test

      - name: plaintext-test
        run: |
          docker exec -e KAFKA_HOST="$KAFKA_HOST" -e KAFKA_PORT="$KAFKA_PLAINTEXT_PORT" -e KAFKA_VERSION="$KAFKA_VERSION" swoole composer test
          docker exec -e KAFKA_HOST="$KAFKA_HOST" -e KAFKA_PORT="$KAFKA_PLAINTEXT_PORT" -e KAFKA_VERSION="$KAFKA_VERSION"  swoole composer swoole-test

      - name: sasl-plaintext-test
        run: |
          docker exec -e KAFKA_HOST="$KAFKA_HOST" -e KAFKA_PORT="$KAFKA_SASL_PLAINTEXT_PORT" -e KAFKA_VERSION="$KAFKA_VERSION" -e KAFKA_SASL="$KAFKA_SASL" swoole composer test
          docker exec -e KAFKA_HOST="$KAFKA_HOST" -e KAFKA_PORT="$KAFKA_SASL_PLAINTEXT_PORT" -e KAFKA_VERSION="$KAFKA_VERSION"  -e KAFKA_SASL="$KAFKA_SASL" swoole composer swoole-test

      - name: sasl-ssl-test
        run: |
          docker exec -e KAFKA_HOST="$KAFKA_HOST" -e KAFKA_PORT="$KAFKA_SASL_SSL_PORT" -e KAFKA_VERSION="$KAFKA_VERSION" -e KAFKA_SASL="$KAFKA_SASL" -e KAFKA_SSL="$KAFKA_SSL" swoole composer test
          docker exec -e KAFKA_HOST="$KAFKA_HOST" -e KAFKA_PORT="$KAFKA_SASL_SSL_PORT" -e KAFKA_VERSION="$KAFKA_VERSION" -e KAFKA_SASL="$KAFKA_SASL" -e KAFKA_SSL="$KAFKA_SSL" swoole composer swoole-test

      - name: ssl-test
        run: |
          docker exec -e KAFKA_HOST="$KAFKA_HOST" -e KAFKA_PORT="$KAFKA_SSL_PORT" -e KAFKA_VERSION="$KAFKA_VERSION" -e KAFKA_SSL="$KAFKA_SSL" swoole composer test
          docker exec -e KAFKA_HOST="$KAFKA_HOST" -e KAFKA_PORT="$KAFKA_SSL_PORT" -e KAFKA_VERSION="$KAFKA_VERSION" -e KAFKA_SSL="$KAFKA_SSL" swoole composer swoole-test
